import { HeaderInfo, Session } from './types';

export const INITIAL_HEADER: HeaderInfo = {
  teacher: "Pr. Soufiane ABID | ذ. سفيان عابيد",
  niveauScolaire: "Tronc Commun",
  moduleEnseignement: "équilibre moteur et intégration par le sport.",
  familleAPS: "Sports de renvoi",
  apsSupport: "Volleyball",
  classe: ""
};

export const MODULES_BY_LEVEL: Record<string, string[]> = {
  "Tronc Commun": [
    "Gestion de l’effort physique",
    "équilibre moteur et intégration par le sport."
  ],
  "1ère année bac": [
    "Engagement moteur et efficience sportive",
    "Effort physique et performance sportive"
  ],
  "2ème année bac": [
    "Efficacité et créativité motrice et sportive",
    "Prise d’initiative et pratique physique et sportive responsable"
  ]
};

export const APS_BY_FAMILY: Record<string, string[]> = {
  "Sports de renvoi": [
    "Volleyball",
    "Tennis",
    "Tennis de table",
    "Badminton"
  ],
  "Sports Collectifs Marquage - démarquage": [
    "Handball",
    "Basketball",
    "Football",
    "Rugby",
    "Ultimate Frisbee"
  ],
  "Athlétisme": [
    "Course de vitesse",
    "Course de demi-fond",
    "Course de haies",
    "Course de relais",
    "Saut en longueur",
    "Saut en hauteur",
    "Triple saut"
  ],
  "Gymnastique": [
    "Gym au sol",
    "Acrogym"
  ],
  "Sports de stratégie": [
    "Échecs"
  ]
};

export const INITIAL_SESSIONS: Session[] = [
  { id: '1', sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Détecter le niveau initial des élèves sur le plan individuel et collectif', date: '', heure: '', duree: '1h', bilan: '', completed: false },
  { id: '2', sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Expliquer les fondamentaux et enrichir les connaissances et le règlement de base de l\'APS', date: '', heure: '', duree: '1h', bilan: '', completed: false },
  { id: '3', sequence: 'Organisation collective pour récupérer la balle', seanceNumber: 3, objectif: 'Se placer et se déplacer pour intercepter la balle et l\'orienter vers le partenaire', date: '', heure: '', duree: '1h', bilan: '', completed: false },
  { id: '4', sequence: 'Organisation collective pour récupérer la balle', seanceNumber: 4, objectif: 'Se placer et se déplacer pour intercepter la balle et l\'orienter vers le partenaire', date: '', heure: '', duree: '1h', bilan: '', completed: false },
  { id: '5', sequence: 'Organisation collective pour récupérer la balle', seanceNumber: 5, objectif: 'Se placer et se déplacer pour intercepter la balle et l\'orienter vers le partenaire', date: '', heure: '', duree: '1h', bilan: '', completed: false },
  { id: '6', sequence: 'Organisation collective pour récupérer la balle', seanceNumber: 6, objectif: 'Se placer et se déplacer pour intercepter la balle et l\'orienter vers le partenaire', date: '', heure: '', duree: '1h', bilan: '', completed: false },
  { id: '7', sequence: 'Séance d’intégration', seanceNumber: 7, objectif: 'Mobilisation des acquisitions précédentes', date: '', heure: '', duree: '1h', bilan: '', completed: false },
  { id: '8', sequence: 'Utilisation des 3 touches de balle pour assurer la continuité du jeu', seanceNumber: 8, objectif: 'Coordonner ses actions pour utiliser les 3 touches et renvoyer la balle', date: '', heure: '', duree: '1h', bilan: '', completed: false },
  { id: '9', sequence: 'Utilisation des 3 touches de balle pour assurer la continuité du jeu', seanceNumber: 9, objectif: 'Coordonner ses actions pour utiliser les 3 touches et renvoyer la balle', date: '', heure: '', duree: '1h', bilan: '', completed: false },
  { id: '10', sequence: 'Utilisation des 3 touches de balle pour assurer la continuité du jeu', seanceNumber: 10, objectif: 'Coordonner ses actions pour utiliser les 3 touches et renvoyer la balle', date: '', heure: '', duree: '1h', bilan: '', completed: false },
  { id: '11', sequence: 'Utilisation des 3 touches de balle pour assurer la continuité du jeu', seanceNumber: 11, objectif: 'Coordonner ses actions pour utiliser les 3 touches et renvoyer la balle', date: '', heure: '', duree: '1h', bilan: '', completed: false },
  { id: '12', sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Déterminer le degré d’acquisition final des élèves sur le plan individuel et collectif', date: '', heure: '', duree: '1h', bilan: '', completed: false },
];

export const VOLLEYBALL_SESSIONS_BY_LEVEL: Record<string, Omit<Session, 'id' | 'date' | 'heure' | 'bilan' | 'completed'>[]> = {
  "Tronc Commun": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Identifier le niveau technique et la capacité à coopérer pour maintenir l’échange', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Règles de base, fair-play et esprit d’équipe en volleyball', duree: '1h' },
    { sequence: 'Coopération défensive', seanceNumber: 3, objectif: 'S’organiser collectivement pour réceptionner et orienter la balle vers le passeur', duree: '1h' },
    { sequence: 'Coopération défensive', seanceNumber: 4, objectif: 'Communiquer pour éviter les zones de conflit et sécuriser le terrain', duree: '1h' },
    { sequence: 'Coopération défensive', seanceNumber: 5, objectif: 'Soutenir ses partenaires lors des phases de réception difficile', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Auto-évaluer son implication dans la solidarité défensive', duree: '1h' },
    { sequence: 'Continuité du jeu', seanceNumber: 7, objectif: 'Utiliser les 3 touches de balle pour construire une attaque collective', duree: '1h' },
    { sequence: 'Continuité du jeu', seanceNumber: 8, objectif: 'Valoriser le rôle du passeur pour faciliter le travail de l’attaquant', duree: '1h' },
    { sequence: 'Continuité du jeu', seanceNumber: 9, objectif: 'Respecter le rythme de ses partenaires pour assurer la fluidité du jeu', duree: '1h' },
    { sequence: 'Continuité du jeu', seanceNumber: 10, objectif: 'Favoriser l’inclusion de tous les joueurs dans la construction du point', duree: '1h' },
    { sequence: 'Continuité du jeu', seanceNumber: 11, objectif: 'Pratique de matchs centrés sur l’entraide et le respect de l’adversaire', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Bilan final : Coopération, Maîtrise technique et Esprit Sportif', duree: '1h' },
  ],
  "1ère année bac": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Evaluer l’efficacité tactique et la gestion des rôles sociaux', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Systèmes de jeu et importance de la communication stratégique', duree: '1h' },
    { sequence: 'Organisation tactique', seanceNumber: 3, objectif: 'Coordonner son placement pour couvrir les zones vulnérables du terrain', duree: '1h' },
    { sequence: 'Organisation tactique', seanceNumber: 4, objectif: 'Anticiper les trajectoires adverses en s’appuyant sur ses partenaires', duree: '1h' },
    { sequence: 'Organisation tactique', seanceNumber: 5, objectif: 'Assumer son rôle spécifique au service du projet collectif', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Co-évaluer la fluidité et l’entraide au sein de l’équipe', duree: '1h' },
    { sequence: 'Construction offensive', seanceNumber: 7, objectif: 'Varier les attaques pour déstabiliser l’adversaire avec intelligence', duree: '1h' },
    { sequence: 'Construction offensive', seanceNumber: 8, objectif: 'Maîtriser le soutien au contre pour sécuriser la défense', duree: '1h' },
    { sequence: 'Construction offensive', seanceNumber: 9, objectif: 'Gérer les moments de pression avec calme et solidarité', duree: '1h' },
    { sequence: 'Construction offensive', seanceNumber: 10, objectif: 'Prendre l’information collective pour jouer vite et juste', duree: '1h' },
    { sequence: 'Construction offensive', seanceNumber: 11, objectif: 'Matchs de préparation favorisant le leadership positif', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Performance collective et respect de l’éthique sportive', duree: '1h' },
  ],
  "2ème année bac": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Analyse de l’organisation collective et du leadership responsable', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Stratégies avancées et gestion éthique de la compétition', duree: '1h' },
    { sequence: 'Maîtrise stratégique', seanceNumber: 3, objectif: 'Maintenir l’équilibre du bloc équipe par un placement autonome', duree: '1h' },
    { sequence: 'Maîtrise stratégique', seanceNumber: 4, objectif: 'Adapter sa stratégie en fonction des forces de l’adversaire', duree: '1h' },
    { sequence: 'Maîtrise stratégique', seanceNumber: 5, objectif: 'Favoriser l’autonomie des joueurs dans la gestion du match', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Analyser son propre impact sur la dynamique et l’ambiance d’équipe', duree: '1h' },
    { sequence: 'Expertise et Responsabilité', seanceNumber: 7, objectif: 'Encadrer et conseiller ses partenaires pour élever le niveau collectif', duree: '1h' },
    { sequence: 'Expertise et Responsabilité', seanceNumber: 8, objectif: 'Gérer l’intensité du jeu tout en préservant l’intégrité des joueurs', duree: '1h' },
    { sequence: 'Expertise et Responsabilité', seanceNumber: 9, objectif: 'Utiliser les temps morts pour réorganiser la tactique avec sérénité', duree: '1h' },
    { sequence: 'Expertise et Responsabilité', seanceNumber: 10, objectif: 'Rechercher l’excellence technique au service d’un jeu fluide', duree: '1h' },
    { sequence: 'Expertise et Responsabilité', seanceNumber: 11, objectif: 'Finalisation du projet de jeu pour le tournoi de fin de cycle', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Bilan final : Leadership, Stratégie et Engagement Citoyen', duree: '1h' },
  ]
};

export const HANDBALL_SESSIONS_BY_LEVEL: Record<string, Omit<Session, 'id' | 'date' | 'heure' | 'bilan' | 'completed'>[]> = {
  "Tronc Commun": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Identifier le niveau technique et la capacité à coopérer en équipe', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Règles d’or, fair-play et respect de l’arbitre', duree: '1h' },
    { sequence: 'Conserver le ballon', seanceNumber: 3, objectif: 'Se démarquer pour offrir des solutions de passe et conserver le ballon', duree: '1h' },
    { sequence: 'Conserver le ballon', seanceNumber: 4, objectif: 'Coopérer avec ses partenaires pour sortir de la zone de pression', duree: '1h' },
    { sequence: 'Conserver le ballon', seanceNumber: 5, objectif: 'Communiquer pour organiser la circulation collective du ballon', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Auto-évaluer son implication dans le jeu collectif et le respect des autres', duree: '1h' },
    { sequence: 'Progresser vers le but', seanceNumber: 7, objectif: 'Utiliser le jeu en mouvement pour progresser vers la zone adverse', duree: '1h' },
    { sequence: 'Progresser vers le but', seanceNumber: 8, objectif: 'Coordonner les montées rapides en impliquant tout le collectif', duree: '1h' },
    { sequence: 'Progresser vers le but', seanceNumber: 9, objectif: 'Valoriser le travail des ailiers pour étirer la défense adverse', duree: '1h' },
    { sequence: 'Progresser vers le but', seanceNumber: 10, objectif: 'S’organiser pour tirer en situation favorable et sécurisée', duree: '1h' },
    { sequence: 'Progresser vers le but', seanceNumber: 11, objectif: 'Pratique de matchs centrés sur la fluidité et l’esprit d’équipe', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Bilan final : Coopération, Progrès et Fair-play', duree: '1h' },
  ],
  "1ère année bac": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Evaluer l’efficacité tactique et le respect des rôles sociaux', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Systèmes de défense et importance de la solidarité collective', duree: '1h' },
    { sequence: 'Fluidité offensive', seanceNumber: 3, objectif: 'Enchaîner les actions rapides pour déstabiliser la défense adverse', duree: '1h' },
    { sequence: 'Fluidité offensive', seanceNumber: 4, objectif: 'Créer des surnombres par des courses croisées et du soutien', duree: '1h' },
    { sequence: 'Fluidité offensive', seanceNumber: 5, objectif: 'Changer de rythme collectivement pour surprendre l’adversaire', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Co-évaluer la fluidité et l’entraide au sein de l’équipe', duree: '1h' },
    { sequence: 'Défense et transition', seanceNumber: 7, objectif: 'S’organiser collectivement pour protéger son but avec détermination', duree: '1h' },
    { sequence: 'Défense et transition', seanceNumber: 8, objectif: 'Réagir vite après récupération (transition attaque/défense solidaire)', duree: '1h' },
    { sequence: 'Défense et transition', seanceNumber: 9, objectif: 'Coordonner les courses de repli pour sécuriser le terrain', duree: '1h' },
    { sequence: 'Défense et transition', seanceNumber: 10, objectif: 'Prendre l’information collective pour jouer juste et efficace', duree: '1h' },
    { sequence: 'Défense et transition', seanceNumber: 11, objectif: 'Matchs à thèmes favorisant la cohésion et le leadership', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Performance collective et respect de l’éthique sportive', duree: '1h' },
  ],
  "2ème année bac": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Analyse de l’organisation collective et du leadership positif', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Stratégies avancées et gestion responsable du match', duree: '1h' },
    { sequence: 'Occupation de l’espace', seanceNumber: 3, objectif: 'Maintenir l’équilibre du bloc équipe par un placement responsable', duree: '1h' },
    { sequence: 'Occupation de l’espace', seanceNumber: 4, objectif: 'Utiliser la largeur pour étirer la défense et créer des brèches', duree: '1h' },
    { sequence: 'Occupation de l’espace', seanceNumber: 5, objectif: 'Occuper les zones stratégiques pour faciliter le jeu de ses partenaires', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Analyser son propre rôle et son impact sur la dynamique d’équipe', duree: '1h' },
    { sequence: 'Maîtrise des rôles tactiques', seanceNumber: 7, objectif: 'Assumer son rôle spécifique au service du projet collectif', duree: '1h' },
    { sequence: 'Maîtrise des rôles tactiques', seanceNumber: 8, objectif: 'Coordonner les compensations pour assurer la sécurité défensive', duree: '1h' },
    { sequence: 'Maîtrise des rôles tactiques', seanceNumber: 9, objectif: 'Gérer les temps forts et faibles avec lucidité et calme', duree: '1h' },
    { sequence: 'Maîtrise des rôles tactiques', seanceNumber: 10, objectif: 'Appliquer des schémas tactiques complexes en toute autonomie', duree: '1h' },
    { sequence: 'Maîtrise des rôles tactiques', seanceNumber: 11, objectif: 'Prendre des initiatives individuelles pour débloquer des situations collectives', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Bilan final : Efficience stratégique et engagement citoyen', duree: '1h' },
  ]
};

export const BASKETBALL_SESSIONS_BY_LEVEL: Record<string, Omit<Session, 'id' | 'date' | 'heure' | 'bilan' | 'completed'>[]> = {
  "Tronc Commun": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Identifier le niveau technique et la capacité à coopérer en équipe', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Règles de base, fair-play et respect de l’adversaire', duree: '1h' },
    { sequence: 'Conserver le ballon', seanceNumber: 3, objectif: 'S’organiser pour offrir des solutions de passe et conserver le ballon', duree: '1h' },
    { sequence: 'Conserver le ballon', seanceNumber: 4, objectif: 'Coopérer avec ses partenaires pour sortir de la zone de pression', duree: '1h' },
    { sequence: 'Conserver le ballon', seanceNumber: 5, objectif: 'Communiquer pour organiser la circulation collective du ballon', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Auto-évaluer son implication dans le jeu collectif et le respect des autres', duree: '1h' },
    { sequence: 'Progresser vers le but', seanceNumber: 7, objectif: 'Utiliser le dribble et la passe pour progresser vers la zone adverse', duree: '1h' },
    { sequence: 'Progresser vers le but', seanceNumber: 8, objectif: 'Coordonner les montées rapides en impliquant tout le collectif', duree: '1h' },
    { sequence: 'Progresser vers le but', seanceNumber: 9, objectif: 'Valoriser le travail d’appui pour faciliter la progression', duree: '1h' },
    { sequence: 'Progresser vers le but', seanceNumber: 10, objectif: 'S’organiser pour tirer en situation favorable et sécurisée', duree: '1h' },
    { sequence: 'Progresser vers le but', seanceNumber: 11, objectif: 'Pratique de matchs centrés sur la fluidité et l’esprit d’équipe', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Bilan final : Coopération, Progrès et Fair-play', duree: '1h' },
  ],
  "1ère année bac": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Evaluer l’efficacité tactique et le respect des rôles sociaux', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Systèmes de défense et importance de la solidarité collective', duree: '1h' },
    { sequence: 'Fluidité offensive', seanceNumber: 3, objectif: 'Enchaîner les actions rapides pour déstabiliser la défense adverse', duree: '1h' },
    { sequence: 'Fluidité offensive', seanceNumber: 4, objectif: 'Créer des surnombres par des courses croisées et du soutien', duree: '1h' },
    { sequence: 'Fluidité offensive', seanceNumber: 5, objectif: 'Changer de rythme collectivement pour surprendre l’adversaire', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Co-évaluer la fluidité et l’entraide au sein de l’équipe', duree: '1h' },
    { sequence: 'Défense et transition', seanceNumber: 7, objectif: 'S’organiser collectivement pour protéger son panier avec détermination', duree: '1h' },
    { sequence: 'Défense et transition', seanceNumber: 8, objectif: 'Réagir vite après récupération (transition attaque/défense solidaire)', duree: '1h' },
    { sequence: 'Défense et transition', seanceNumber: 9, objectif: 'Coordonner les courses de repli pour sécuriser le terrain', duree: '1h' },
    { sequence: 'Défense et transition', seanceNumber: 10, objectif: 'Prendre l’information collective pour jouer juste et efficace', duree: '1h' },
    { sequence: 'Défense et transition', seanceNumber: 11, objectif: 'Matchs à thèmes favorisant la cohésion et le leadership', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Performance collective et respect de l’éthique sportive', duree: '1h' },
  ],
  "2ème année bac": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Analyse de l’organisation collective et du leadership positif', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Stratégies avancées et gestion responsable du match', duree: '1h' },
    { sequence: 'Occupation de l’espace', seanceNumber: 3, objectif: 'Maintenir l’équilibre du bloc équipe par un placement responsable', duree: '1h' },
    { sequence: 'Occupation de l’espace', seanceNumber: 4, objectif: 'Utiliser la largeur pour étirer la défense et créer des brèches', duree: '1h' },
    { sequence: 'Occupation de l’espace', seanceNumber: 5, objectif: 'Occuper les zones stratégiques pour faciliter le jeu de ses partenaires', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Analyser son propre rôle et son impact sur la dynamique d’équipe', duree: '1h' },
    { sequence: 'Maîtrise des rôles tactiques', seanceNumber: 7, objectif: 'Assumer son rôle spécifique au service du projet collectif', duree: '1h' },
    { sequence: 'Maîtrise des rôles tactiques', seanceNumber: 8, objectif: 'Coordonner les compensations pour assurer la sécurité défensive', duree: '1h' },
    { sequence: 'Maîtrise des rôles tactiques', seanceNumber: 9, objectif: 'Gérer les temps forts et faibles avec lucidité et calme', duree: '1h' },
    { sequence: 'Maîtrise des rôles tactiques', seanceNumber: 10, objectif: 'Appliquer des schémas tactiques complexes en toute autonomie', duree: '1h' },
    { sequence: 'Maîtrise des rôles tactiques', seanceNumber: 11, objectif: 'Prendre des initiatives individuelles pour débloquer des situations collectives', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Bilan final : Efficience stratégique et engagement citoyen', duree: '1h' },
  ]
};

export const FOOTBALL_SESSIONS_BY_LEVEL: Record<string, Omit<Session, 'id' | 'date' | 'heure' | 'bilan' | 'completed'>[]> = {
  "Tronc Commun": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Identifier le niveau technique et la capacité à coopérer en équipe', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Règles de base, fair-play et respect de l’arbitre', duree: '1h' },
    { sequence: 'Conserver le ballon', seanceNumber: 3, objectif: 'Coopérer avec ses partenaires pour conserver le ballon collectivement', duree: '1h' },
    { sequence: 'Conserver le ballon', seanceNumber: 4, objectif: 'S’organiser pour offrir des solutions de passe et soutenir le porteur', duree: '1h' },
    { sequence: 'Conserver le ballon', seanceNumber: 5, objectif: 'Communiquer pour sortir collectivement de la zone de pression', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Auto-évaluer son implication dans le jeu collectif', duree: '1h' },
    { sequence: 'Progresser vers le but', seanceNumber: 7, objectif: 'Utiliser le jeu court pour progresser ensemble vers la cible', duree: '1h' },
    { sequence: 'Progresser vers le but', seanceNumber: 8, objectif: 'Coordonner les déplacements pour franchir les lignes adverses', duree: '1h' },
    { sequence: 'Progresser vers le but', seanceNumber: 9, objectif: 'Valoriser le travail des latéraux pour centrer et finir', duree: '1h' },
    { sequence: 'Progresser vers le but', seanceNumber: 10, objectif: 'Réaliser des transitions rapides en respectant le placement des autres', duree: '1h' },
    { sequence: 'Progresser vers le but', seanceNumber: 11, objectif: 'Finaliser les actions en privilégiant la meilleure solution collective', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Bilan des compétences motrices et de l’esprit d’équipe', duree: '1h' },
  ],
  "1ère année bac": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Evaluer l’efficacité tactique et le respect des rôles sociaux', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Systèmes de jeu et importance de la solidarité défensive', duree: '1h' },
    { sequence: 'Jouer en mouvement', seanceNumber: 3, objectif: 'Enchaîner les actions en mouvement pour aider le partenaire', duree: '1h' },
    { sequence: 'Jouer en mouvement', seanceNumber: 4, objectif: 'Créer des triangles de jeu pour une progression fluide et solidaire', duree: '1h' },
    { sequence: 'Jouer en mouvement', seanceNumber: 5, objectif: 'Changer de rythme collectivement pour déstabiliser l’adversaire', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Co-évaluer la fluidité et l’entraide au sein de l’équipe', duree: '1h' },
    { sequence: 'Montée rapide', seanceNumber: 7, objectif: 'Exploiter les espaces après récupération en impliquant tout le bloc', duree: '1h' },
    { sequence: 'Montée rapide', seanceNumber: 8, objectif: 'Réaliser des contre-attaques en gérant le surnombre avec altruisme', duree: '1h' },
    { sequence: 'Montée rapide', seanceNumber: 9, objectif: 'Coordonner les courses de soutien pour sécuriser l’attaque', duree: '1h' },
    { sequence: 'Montée rapide', seanceNumber: 10, objectif: 'Prendre l’information pour jouer vite et juste pour le collectif', duree: '1h' },
    { sequence: 'Montée rapide', seanceNumber: 11, objectif: 'Efficacité devant le but en situation de vitesse et de pression', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Performance collective et respect de l’éthique sportive', duree: '1h' },
  ],
  "2ème année bac": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Analyse de l’organisation collective et du leadership positif', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Stratégies avancées et gestion responsable du match', duree: '1h' },
    { sequence: 'Occupation rationnelle de l’espace', seanceNumber: 3, objectif: 'Maintenir l’équilibre du bloc équipe par un placement responsable', duree: '1h' },
    { sequence: 'Occupation rationnelle de l’espace', seanceNumber: 4, objectif: 'Utiliser la largeur pour étirer la défense et créer des brèches', duree: '1h' },
    { sequence: 'Occupation rationnelle de l’espace', seanceNumber: 5, objectif: 'Occuper les zones stratégiques pour faciliter le jeu de ses partenaires', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Analyser son propre rôle et son impact sur la dynamique d’équipe', duree: '1h' },
    { sequence: 'Maîtrise des rôles tactiques', seanceNumber: 7, objectif: 'Assumer son rôle spécifique au service du projet collectif', duree: '1h' },
    { sequence: 'Maîtrise des rôles tactiques', seanceNumber: 8, objectif: 'Coordonner les compensations pour assurer la sécurité défensive', duree: '1h' },
    { sequence: 'Maîtrise des rôles tactiques', seanceNumber: 9, objectif: 'Gérer les temps forts et faibles avec lucidité et calme', duree: '1h' },
    { sequence: 'Maîtrise des rôles tactiques', seanceNumber: 10, objectif: 'Appliquer des schémas tactiques en respectant les consignes du coach', duree: '1h' },
    { sequence: 'Maîtrise des rôles tactiques', seanceNumber: 11, objectif: 'Prendre des initiatives individuelles pour débloquer des situations collectives', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Bilan final : Efficience stratégique et engagement citoyen', duree: '1h' },
  ]
};

export const ATHLETISME_SESSIONS_BY_LEVEL: Record<string, Omit<Session, 'id' | 'date' | 'heure' | 'bilan' | 'completed'>[]> = {
  "Tronc Commun": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Mesurer sa performance et identifier ses besoins d’entraide', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Sécurité, échauffement et respect des zones de pratique', duree: '1h' },
    { sequence: 'Technique de course/saut', seanceNumber: 3, objectif: 'Améliorer sa posture en écoutant les conseils de ses pairs', duree: '1h' },
    { sequence: 'Technique de course/saut', seanceNumber: 4, objectif: 'Travailler la phase de poussée en observant ses camarades', duree: '1h' },
    { sequence: 'Technique de course/saut', seanceNumber: 5, objectif: 'Optimiser le franchissement en respectant le rythme de chacun', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Donner et recevoir un feedback constructif sur la technique', duree: '1h' },
    { sequence: 'Amélioration de la performance', seanceNumber: 7, objectif: 'Développer sa puissance tout en encourageant les autres', duree: '1h' },
    { sequence: 'Amélioration de la performance', seanceNumber: 8, objectif: 'Travailler la régularité en se fixant des défis personnels', duree: '1h' },
    { sequence: 'Amélioration de la performance', seanceNumber: 9, objectif: 'Gérer son effort en étant attentif à ses sensations physiques', duree: '1h' },
    { sequence: 'Amélioration de la performance', seanceNumber: 10, objectif: 'Affiner la technique en situation de mini-compétition fraternelle', duree: '1h' },
    { sequence: 'Amélioration de la performance', seanceNumber: 11, objectif: 'Se concentrer et se préparer mentalement à l’effort final', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Bilan final : Progrès personnel et respect des règles', duree: '1h' },
  ],
  "1ère année bac": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Bilan des capacités et mise en place de binômes d’observation', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Physiologie de l’effort et gestion autonome de l’entraînement', duree: '1h' },
    { sequence: 'Efficience motrice', seanceNumber: 3, objectif: 'Réduire les mouvements parasites par une analyse croisée', duree: '1h' },
    { sequence: 'Efficience motrice', seanceNumber: 4, objectif: 'Travailler la synchronisation en s’appuyant sur des repères visuels', duree: '1h' },
    { sequence: 'Efficience motrice', seanceNumber: 5, objectif: 'Optimiser le rapport amplitude/fréquence selon son profil', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Analyser la performance d’un pair à l’aide d’une grille de critères', duree: '1h' },
    { sequence: 'Gestion de l’effort', seanceNumber: 7, objectif: 'Apprendre à répartir son énergie de manière stratégique', duree: '1h' },
    { sequence: 'Gestion de l’effort', seanceNumber: 8, objectif: 'Maintenir sa technique malgré la fatigue (persévérance)', duree: '1h' },
    { sequence: 'Gestion de l’effort', seanceNumber: 9, objectif: 'Maîtriser les phases critiques (départ, virage) avec précision', duree: '1h' },
    { sequence: 'Gestion de l’effort', seanceNumber: 10, objectif: 'Développer des stratégies de course en respectant les adversaires', duree: '1h' },
    { sequence: 'Gestion de l’effort', seanceNumber: 11, objectif: 'Simulations de compétition centrées sur le dépassement de soi', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Validation de la performance et de la capacité d’analyse', duree: '1h' },
  ],
  "2ème année bac": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Analyse fine des points forts et engagement dans un projet de performance', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Planification de l’entraînement et hygiène de vie du sportif', duree: '1h' },
    { sequence: 'Optimisation technique', seanceNumber: 3, objectif: 'Recherche de la précision gestuelle par l’auto-correction', duree: '1h' },
    { sequence: 'Optimisation technique', seanceNumber: 4, objectif: 'Ajuster sa technique en s’adaptant aux contraintes de l’épreuve', duree: '1h' },
    { sequence: 'Optimisation technique', seanceNumber: 5, objectif: 'Utiliser la vidéo pour une analyse réflexive de sa pratique', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Test de performance et ajustement du projet personnel', duree: '1h' },
    { sequence: 'Performance et responsabilité', seanceNumber: 7, objectif: 'S’auto-évaluer avec honnêteté et rigueur', duree: '1h' },
    { sequence: 'Performance et responsabilité', seanceNumber: 8, objectif: 'Gérer le stress de la compétition par des techniques de relaxation', duree: '1h' },
    { sequence: 'Performance et responsabilité', seanceNumber: 9, objectif: 'Maîtriser les règlements et assumer des rôles de juge/officiel', duree: '1h' },
    { sequence: 'Performance et responsabilité', seanceNumber: 10, objectif: 'Rechercher l’excellence tout en préservant l’éthique sportive', duree: '1h' },
    { sequence: 'Performance et responsabilité', seanceNumber: 11, objectif: 'Finalisation du projet de performance individuelle et collective', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Bilan final : Performance, Autonomie et Citoyenneté', duree: '1h' },
  ]
};

export const GYMNASTIQUE_SESSIONS_BY_LEVEL: Record<string, Omit<Session, 'id' | 'date' | 'heure' | 'bilan' | 'completed'>[]> = {
  "Tronc Commun": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Identifier le répertoire moteur et la capacité à aider ses camarades', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Sécurité, parade et importance de la confiance mutuelle', duree: '1h' },
    { sequence: 'Maîtrise des éléments de base', seanceNumber: 3, objectif: 'Réaliser des roulades en assurant la sécurité de son partenaire', duree: '1h' },
    { sequence: 'Maîtrise des éléments de base', seanceNumber: 4, objectif: 'Travailler l’équilibre en s’appuyant sur l’aide d’un camarade', duree: '1h' },
    { sequence: 'Maîtrise des éléments de base', seanceNumber: 5, objectif: 'Apprendre les sauts et réceptions en respectant l’espace d’autrui', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Auto-évaluer sa posture et sa capacité à être un bon pareur', duree: '1h' },
    { sequence: 'Enchaînement simple', seanceNumber: 7, objectif: 'Lier deux éléments en harmonie avec le rythme du groupe', duree: '1h' },
    { sequence: 'Enchaînement simple', seanceNumber: 8, objectif: 'Respecter l’esthétique et encourager la réussite des autres', duree: '1h' },
    { sequence: 'Enchaînement simple', seanceNumber: 9, objectif: 'Maintenir la concentration pour assurer la fluidité collective', duree: '1h' },
    { sequence: 'Enchaînement simple', seanceNumber: 10, objectif: 'Utiliser l’espace de manière créative et respectueuse', duree: '1h' },
    { sequence: 'Enchaînement simple', seanceNumber: 11, objectif: 'Présenter son travail avec humilité et écouter les critiques', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Bilan final : Maîtrise technique et solidarité', duree: '1h' },
  ],
  "1ère année bac": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Bilan technique et mise en place de projets d’entraide', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Code de pointage et critères d’appréciation artistique', duree: '1h' },
    { sequence: 'Complexification technique', seanceNumber: 3, objectif: 'Réaliser des éléments complexes en s’entraidant activement', duree: '1h' },
    { sequence: 'Complexification technique', seanceNumber: 4, objectif: 'Améliorer l’amplitude par un travail de souplesse partagé', duree: '1h' },
    { sequence: 'Complexification technique', seanceNumber: 5, objectif: 'Travailler la force et le gainage en binôme de motivation', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Analyser la prestation d’un pair selon des critères précis', duree: '1h' },
    { sequence: 'Composition d’enchaînement', seanceNumber: 7, objectif: 'Choisir des éléments valorisant ses propres capacités', duree: '1h' },
    { sequence: 'Composition d’enchaînement', seanceNumber: 8, objectif: 'Travailler l’expression corporelle pour communiquer une émotion', duree: '1h' },
    { sequence: 'Composition d’enchaînement', seanceNumber: 9, objectif: 'Assurer la continuité esthétique de sa production', duree: '1h' },
    { sequence: 'Composition d’enchaînement', seanceNumber: 10, objectif: 'Gérer son stress devant un public (ses camarades)', duree: '1h' },
    { sequence: 'Composition d’enchaînement', seanceNumber: 11, objectif: 'Répétition générale centrée sur la confiance en soi', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Performance sur l’enchaînement et qualité de l’observation', duree: '1h' },
  ],
  "2ème année bac": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Analyse des capacités de création et engagement responsable', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Concevoir un projet artistique porteur de sens social', duree: '1h' },
    { sequence: 'Excellence technique', seanceNumber: 3, objectif: 'Perfectionner ses gestes par une auto-analyse rigoureuse', duree: '1h' },
    { sequence: 'Excellence technique', seanceNumber: 4, objectif: 'Optimiser les réceptions pour préserver son intégrité physique', duree: '1h' },
    { sequence: 'Excellence technique', seanceNumber: 5, objectif: 'Travailler la fluidité pour une harmonie visuelle maximale', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Test de l’enchaînement et retour critique constructif', duree: '1h' },
    { sequence: 'Projet artistique complexe', seanceNumber: 7, objectif: 'Intégrer une dimension originale et personnelle au projet', duree: '1h' },
    { sequence: 'Projet artistique complexe', seanceNumber: 8, objectif: 'Gérer sa présence scénique et son rapport aux juges', duree: '1h' },
    { sequence: 'Projet artistique complexe', seanceNumber: 9, objectif: 'S’auto-corriger en utilisant les outils numériques', duree: '1h' },
    { sequence: 'Projet artistique complexe', seanceNumber: 10, objectif: 'Maîtriser le temps et l’espace de manière autonome', duree: '1h' },
    { sequence: 'Projet artistique complexe', seanceNumber: 11, objectif: 'Finalisation de la prestation avec une exigence d’excellence', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Présentation finale du projet gymnique et bilan citoyen', duree: '1h' },
  ]
};

export const STRATEGIE_SESSIONS_BY_LEVEL: Record<string, Omit<Session, 'id' | 'date' | 'heure' | 'bilan' | 'completed'>[]> = {
  "Tronc Commun": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Evaluer la connaissance des règles et le respect de l’adversaire', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Histoire, valeurs et éthique du sport de l’esprit', duree: '1h' },
    { sequence: 'Fondamentaux', seanceNumber: 3, objectif: 'Maîtriser le mouvement des pièces avec calme et réflexion', duree: '1h' },
    { sequence: 'Fondamentaux', seanceNumber: 4, objectif: 'Comprendre l’échec et mat comme une fin de partie respectueuse', duree: '1h' },
    { sequence: 'Fondamentaux', seanceNumber: 5, objectif: 'Apprendre les coups spéciaux en restant attentif au partenaire', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Résoudre des problèmes simples en s’entraidant', duree: '1h' },
    { sequence: 'Tactiques de base', seanceNumber: 7, objectif: 'Identifier les opportunités tactiques sans précipitation', duree: '1h' },
    { sequence: 'Tactiques de base', seanceNumber: 8, objectif: 'Utiliser le clouage en comprenant la stratégie adverse', duree: '1h' },
    { sequence: 'Tactiques de base', seanceNumber: 9, objectif: 'Apprécier la valeur des pièces pour une gestion responsable', duree: '1h' },
    { sequence: 'Tactiques de base', seanceNumber: 10, objectif: 'Développer son jeu en respectant l’équilibre de l’échiquier', duree: '1h' },
    { sequence: 'Tactiques de base', seanceNumber: 11, objectif: 'Pratiquer des parties amicales suivies d’une analyse commune', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Tournoi de classe fondé sur le fair-play et la réflexion', duree: '1h' },
  ],
  "1ère année bac": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Bilan tactique et capacité à analyser ses propres erreurs', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Principes d’ouverture et importance de la patience', duree: '1h' },
    { sequence: 'Tactique avancée', seanceNumber: 3, objectif: 'Utiliser des combinaisons complexes avec lucidité', duree: '1h' },
    { sequence: 'Tactique avancée', seanceNumber: 4, objectif: 'Maîtriser le sacrifice comme un choix stratégique réfléchi', duree: '1h' },
    { sequence: 'Tactique avancée', seanceNumber: 5, objectif: 'Calculer des variantes en restant concentré et serein', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Co-analyser des positions complexes avec un camarade', duree: '1h' },
    { sequence: 'Stratégie de milieu de jeu', seanceNumber: 7, objectif: 'Comprendre la structure de pions pour un plan à long terme', duree: '1h' },
    { sequence: 'Stratégie de milieu de jeu', seanceNumber: 8, objectif: 'Centraliser ses forces pour une action coordonnée', duree: '1h' },
    { sequence: 'Stratégie de milieu de jeu', seanceNumber: 9, objectif: 'Identifier les plans adverses pour mieux y répondre', duree: '1h' },
    { sequence: 'Stratégie de milieu de jeu', seanceNumber: 10, objectif: 'Gérer son temps de réflexion de manière autonome', duree: '1h' },
    { sequence: 'Stratégie de milieu de jeu', seanceNumber: 11, objectif: 'Analyser des parties historiques pour s’en inspirer', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Compétition interne valorisant la persévérance', duree: '1h' },
  ],
  "2ème année bac": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Analyse du style de jeu et engagement dans un projet de progrès', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Théorie des finales et gestion de la fin de partie', duree: '1h' },
    { sequence: 'Expertise stratégique', seanceNumber: 3, objectif: 'Maîtriser les finales avec une précision mathématique', duree: '1h' },
    { sequence: 'Expertise stratégique', seanceNumber: 4, objectif: 'Comprendre les avantages positionnels subtils', duree: '1h' },
    { sequence: 'Expertise stratégique', seanceNumber: 5, objectif: 'Elaborer des plans complexes en toute autonomie', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Prendre des décisions difficiles sous pression temporelle', duree: '1h' },
    { sequence: 'Maîtrise psychologique', seanceNumber: 7, objectif: 'Gérer ses émotions lors des moments critiques du match', duree: '1h' },
    { sequence: 'Maîtrise psychologique', seanceNumber: 8, objectif: 'Préparer une stratégie spécifique avec rigueur', duree: '1h' },
    { sequence: 'Maîtrise psychologique', seanceNumber: 9, objectif: 'Utiliser l’informatique pour une auto-évaluation objective', duree: '1h' },
    { sequence: 'Maîtrise psychologique', seanceNumber: 10, objectif: 'Développer une pensée critique sur sa propre pratique', duree: '1h' },
    { sequence: 'Maîtrise psychologique', seanceNumber: 11, objectif: 'Simulations de tournoi officiel avec respect du protocole', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Bilan final : Expertise, Maîtrise de soi et Citoyenneté', duree: '1h' },
  ]
};

export const RACKET_SESSIONS_BY_LEVEL: Record<string, Omit<Session, 'id' | 'date' | 'heure' | 'bilan' | 'completed'>[]> = {
  "Tronc Commun": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Identifier son niveau de jeu et sa capacité à jouer avec un partenaire', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Règles du jeu, comptage des points et respect de l’adversaire', duree: '1h' },
    { sequence: 'Maîtrise de l’échange', seanceNumber: 3, objectif: 'Coopérer pour maintenir l’échange et assurer la continuité du jeu', duree: '1h' },
    { sequence: 'Maîtrise de l’échange', seanceNumber: 4, objectif: 'S’organiser pour renvoyer le projectile de manière sécurisée', duree: '1h' },
    { sequence: 'Maîtrise de l’échange', seanceNumber: 5, objectif: 'Adapter son placement pour faciliter le renvoi et aider son partenaire', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Auto-évaluer sa régularité et son attitude bienveillante', duree: '1h' },
    { sequence: 'Rupture de l’échange', seanceNumber: 7, objectif: 'Rechercher les espaces libres pour mettre l’adversaire en difficulté', duree: '1h' },
    { sequence: 'Rupture de l’échange', seanceNumber: 8, objectif: 'Varier les trajectoires tout en respectant les règles de sécurité', duree: '1h' },
    { sequence: 'Rupture de l’échange', seanceNumber: 9, objectif: 'Se replacer rapidement pour anticiper la réponse adverse', duree: '1h' },
    { sequence: 'Rupture de l’échange', seanceNumber: 10, objectif: 'Utiliser le revers comme solution de dégagement et de défense', duree: '1h' },
    { sequence: 'Rupture de l’échange', seanceNumber: 11, objectif: 'Pratique de matchs arbitrés par les élèves (responsabilisation)', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Bilan final : Progrès technique, Fair-play et Arbitrage', duree: '1h' },
  ],
  "1ère année bac": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Evaluer l’efficacité tactique et la gestion émotionnelle en match', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Tactiques de double et importance de la communication', duree: '1h' },
    { sequence: 'Jeu en double', seanceNumber: 3, objectif: 'Se coordonner avec son partenaire pour couvrir le terrain', duree: '1h' },
    { sequence: 'Jeu en double', seanceNumber: 4, objectif: 'Communiquer efficacement pour éviter les conflits de placement', duree: '1h' },
    { sequence: 'Jeu en double', seanceNumber: 5, objectif: 'Soutenir son partenaire dans les moments difficiles du match', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Co-évaluer la complémentarité et la solidarité de l’équipe', duree: '1h' },
    { sequence: 'Stratégie offensive', seanceNumber: 7, objectif: 'Créer des situations d’attaque par des coups précis', duree: '1h' },
    { sequence: 'Stratégie offensive', seanceNumber: 8, objectif: 'Exploiter les faiblesses de l’adversaire avec lucidité', duree: '1h' },
    { sequence: 'Stratégie offensive', seanceNumber: 9, objectif: 'Prendre l’initiative au filet tout en protégeant son partenaire', duree: '1h' },
    { sequence: 'Stratégie offensive', seanceNumber: 10, objectif: 'Gérer la pression lors des points décisifs', duree: '1h' },
    { sequence: 'Stratégie offensive', seanceNumber: 11, objectif: 'Tournoi de classe favorisant l’intégration et le respect', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Performance collective, Stratégie et Esprit d’équipe', duree: '1h' },
  ],
  "2ème année bac": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Analyse de l’autonomie tactique et de l’engagement citoyen', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Conception d’un projet de jeu et gestion de l’entraînement', duree: '1h' },
    { sequence: 'Projet de jeu', seanceNumber: 3, objectif: 'Identifier ses points forts et construire une stratégie adaptée', duree: '1h' },
    { sequence: 'Projet de jeu', seanceNumber: 4, objectif: 'Adapter son jeu en fonction du profil de l’adversaire', duree: '1h' },
    { sequence: 'Projet de jeu', seanceNumber: 5, objectif: 'Gérer ses émotions et rester concentré face à la difficulté', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Bilan intermédiaire du projet personnel et ajustements', duree: '1h' },
    { sequence: 'Expertise et arbitrage', seanceNumber: 7, objectif: 'Assumer le rôle d’arbitre principal avec autorité et bienveillance', duree: '1h' },
    { sequence: 'Expertise et arbitrage', seanceNumber: 8, objectif: 'Conseiller un camarade pour améliorer sa performance (coaching)', duree: '1h' },
    { sequence: 'Expertise et arbitrage', seanceNumber: 9, objectif: 'Organiser un tournoi en gérant les rotations et les scores', duree: '1h' },
    { sequence: 'Expertise et arbitrage', seanceNumber: 10, objectif: 'Rechercher l’excellence technique dans le respect de l’éthique', duree: '1h' },
    { sequence: 'Expertise et arbitrage', seanceNumber: 11, objectif: 'Finalisation de la préparation au tournoi final', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Bilan final : Autonomie, Expertise et Responsabilité', duree: '1h' },
  ]
};

export const RUGBY_SESSIONS_BY_LEVEL: Record<string, Omit<Session, 'id' | 'date' | 'heure' | 'bilan' | 'completed'>[]> = {
  "Tronc Commun": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Identifier l’appréhension du contact et la capacité à s’engager collectivement', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Règles de sécurité, respect de l’intégrité physique et de l’arbitre', duree: '1h' },
    { sequence: 'Avancer et soutenir', seanceNumber: 3, objectif: 'Coopérer pour porter le ballon vers l’avant en toute sécurité', duree: '1h' },
    { sequence: 'Avancer et soutenir', seanceNumber: 4, objectif: 'S’organiser pour soutenir le porteur de balle et assurer la continuité', duree: '1h' },
    { sequence: 'Avancer et soutenir', seanceNumber: 5, objectif: 'Communiquer pour coordonner les passes et éviter les pertes de balle', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Auto-évaluer son engagement physique et son respect des consignes', duree: '1h' },
    { sequence: 'Franchir et marquer', seanceNumber: 7, objectif: 'Utiliser les espaces libres pour progresser sans chercher le contact systématique', duree: '1h' },
    { sequence: 'Franchir et marquer', seanceNumber: 8, objectif: 'Coordonner les actions pour créer des situations de marque collectives', duree: '1h' },
    { sequence: 'Franchir et marquer', seanceNumber: 9, objectif: 'Apprendre à plaquer et à chuter en respectant la sécurité de l’autre', duree: '1h' },
    { sequence: 'Franchir et marquer', seanceNumber: 10, objectif: 'S’organiser solidairement en défense pour protéger son camp', duree: '1h' },
    { sequence: 'Franchir et marquer', seanceNumber: 11, objectif: 'Pratique de matchs centrés sur le fair-play et l’esprit d’équipe', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Bilan final : Courage, Solidarité et Respect des règles', duree: '1h' },
  ],
  "1ère année bac": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Evaluer l’efficacité tactique et la solidarité dans l’effort', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Systèmes de jeu et importance de la cohésion d’équipe', duree: '1h' },
    { sequence: 'Continuité du jeu', seanceNumber: 3, objectif: 'Assurer la libération du ballon pour faciliter le jeu de ses partenaires', duree: '1h' },
    { sequence: 'Continuité du jeu', seanceNumber: 4, objectif: 'Enchaîner les actions collectives pour maintenir la pression sur l’adversaire', duree: '1h' },
    { sequence: 'Continuité du jeu', seanceNumber: 5, objectif: 'Assumer son rôle dans les phases de combat (rucks) avec lucidité', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Co-évaluer la fluidité du jeu et l’entraide au sein du groupe', duree: '1h' },
    { sequence: 'Organisation offensive', seanceNumber: 7, objectif: 'Créer des surnombres par des lancements de jeu coordonnés', duree: '1h' },
    { sequence: 'Organisation offensive', seanceNumber: 8, objectif: 'Fixer la défense pour libérer des espaces pour ses coéquipiers', duree: '1h' },
    { sequence: 'Organisation offensive', seanceNumber: 9, objectif: 'S’organiser collectivement lors des phases statiques (mêlées, touches)', duree: '1h' },
    { sequence: 'Organisation offensive', seanceNumber: 10, objectif: 'Prendre des décisions rapides au service du projet collectif', duree: '1h' },
    { sequence: 'Organisation offensive', seanceNumber: 11, objectif: 'Matchs à thèmes favorisant la communication et le leadership', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Performance collective, Engagement et Ethique sportive', duree: '1h' },
  ],
  "2ème année bac": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Analyse de l’intelligence tactique et du leadership positif', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Stratégies avancées et gestion responsable des situations de match', duree: '1h' },
    { sequence: 'Maîtrise stratégique', seanceNumber: 3, objectif: 'Alterner les formes de jeu (groupé/déployé) de manière pertinente', duree: '1h' },
    { sequence: 'Maîtrise stratégique', seanceNumber: 4, objectif: 'Adapter collectivement la stratégie face à l’opposition', duree: '1h' },
    { sequence: 'Maîtrise stratégique', seanceNumber: 5, objectif: 'Gérer les moments de pression avec calme et solidarité', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Analyser son impact sur la dynamique d’équipe et ajuster son comportement', duree: '1h' },
    { sequence: 'Projet de jeu expert', seanceNumber: 7, objectif: 'Assumer pleinement son rôle spécifique au service du collectif', duree: '1h' },
    { sequence: 'Projet de jeu expert', seanceNumber: 8, objectif: 'Coordonner les actions complexes en garantissant la sécurité de tous', duree: '1h' },
    { sequence: 'Projet de jeu expert', seanceNumber: 9, objectif: 'Maintenir une discipline irréprochable et un respect absolu de l’arbitre', duree: '1h' },
    { sequence: 'Projet de jeu expert', seanceNumber: 10, objectif: 'Prendre des initiatives pour débloquer des situations difficiles', duree: '1h' },
    { sequence: 'Projet de jeu expert', seanceNumber: 11, objectif: 'Finalisation de la stratégie pour le tournoi dans un esprit de fraternité', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Bilan final : Efficience stratégique, Responsabilité et Citoyenneté', duree: '1h' },
  ]
};

export const ULTIMATE_FRISBEE_SESSIONS_BY_LEVEL: Record<string, Omit<Session, 'id' | 'date' | 'heure' | 'bilan' | 'completed'>[]> = {
  "Tronc Commun": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Identifier la capacité à coopérer et la compréhension de l’auto-arbitrage', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Assimiler l’Esprit du Jeu (Spirit of the Game), le respect et la non-violence', duree: '1h' },
    { sequence: 'Lancer et réceptionner', seanceNumber: 3, objectif: 'S’entraider pour maîtriser les lancers de base et assurer la continuité', duree: '1h' },
    { sequence: 'Lancer et réceptionner', seanceNumber: 4, objectif: 'Coopérer avec ses partenaires pour progresser collectivement vers la zone', duree: '1h' },
    { sequence: 'Lancer et réceptionner', seanceNumber: 5, objectif: 'Communiquer pour offrir des solutions de passe et soutenir le porteur', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Auto-évaluer son implication dans le groupe et son respect du fair-play', duree: '1h' },
    { sequence: 'Progresser collectivement', seanceNumber: 7, objectif: 'S’organiser spatialement pour faciliter le jeu de ses coéquipiers', duree: '1h' },
    { sequence: 'Progresser collectivement', seanceNumber: 8, objectif: 'Développer une communication positive pour coordonner les actions', duree: '1h' },
    { sequence: 'Progresser collectivement', seanceNumber: 9, objectif: 'Assumer l’auto-arbitrage avec honnêteté et respect de l’adversaire', duree: '1h' },
    { sequence: 'Progresser collectivement', seanceNumber: 10, objectif: 'Valoriser l’inclusion et l’implication de tous les membres de l’équipe', duree: '1h' },
    { sequence: 'Progresser collectivement', seanceNumber: 11, objectif: 'Pratique de matchs centrés sur la solidarité, la fluidité et le respect', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Bilan final : Coopération, Esprit du Jeu et Citoyenneté', duree: '1h' },
  ],
  "1ère année bac": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Bilan de l’efficacité collective et de la gestion pacifique des conflits', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Stratégies d’équipe et importance de la responsabilité individuelle', duree: '1h' },
    { sequence: 'Fluidité offensive', seanceNumber: 3, objectif: 'Enchaîner les passes pour créer une dynamique de réussite collective', duree: '1h' },
    { sequence: 'Fluidité offensive', seanceNumber: 4, objectif: 'Créer des espaces par des courses solidaires et du soutien mutuel', duree: '1h' },
    { sequence: 'Fluidité offensive', seanceNumber: 5, objectif: 'Assumer différents rôles (lanceur/receveur) au service de l’équipe', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Observer et conseiller une autre équipe de manière constructive', duree: '1h' },
    { sequence: 'Défense et transition', seanceNumber: 7, objectif: 'S’organiser collectivement en défense sans aucun contact physique', duree: '1h' },
    { sequence: 'Défense et transition', seanceNumber: 8, objectif: 'Réagir solidairement lors des transitions attaque/défense', duree: '1h' },
    { sequence: 'Défense et transition', seanceNumber: 9, objectif: 'Gérer les désaccords par le dialogue et la médiation sur le terrain', duree: '1h' },
    { sequence: 'Défense et transition', seanceNumber: 10, objectif: 'Prendre des décisions tactiques en concertation avec ses partenaires', duree: '1h' },
    { sequence: 'Défense et transition', seanceNumber: 11, objectif: 'Matchs à thèmes favorisant la mixité, l’entraide et le leadership', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Performance collective, Stratégie et Maturité dans l’auto-arbitrage', duree: '1h' },
  ],
  "2ème année bac": [
    { sequence: 'Evaluation diagnostique', seanceNumber: 1, objectif: 'Analyse de l’autonomie, du leadership positif et de l’esprit sportif', duree: '1h' },
    { sequence: 'Séance théorique', seanceNumber: 2, objectif: 'Conception d’un projet de jeu éthique et gestion de tournoi', duree: '1h' },
    { sequence: 'Expertise stratégique', seanceNumber: 3, objectif: 'Mettre en œuvre des tactiques complexes en parfaite coordination', duree: '1h' },
    { sequence: 'Expertise stratégique', seanceNumber: 4, objectif: 'Adapter collectivement la stratégie face aux difficultés rencontrées', duree: '1h' },
    { sequence: 'Expertise stratégique', seanceNumber: 5, objectif: 'Favoriser l’autonomie et la prise d’initiative de chaque joueur', duree: '1h' },
    { sequence: 'Evaluation formative', seanceNumber: 6, objectif: 'Bilan critique du projet de jeu et régulation collective', duree: '1h' },
    { sequence: 'Responsabilité et Leadership', seanceNumber: 7, objectif: 'Encadrer, motiver et conseiller ses partenaires avec bienveillance', duree: '1h' },
    { sequence: 'Responsabilité et Leadership', seanceNumber: 8, objectif: 'Gérer l’intensité du match tout en garantissant un fair-play absolu', duree: '1h' },
    { sequence: 'Responsabilité et Leadership', seanceNumber: 9, objectif: 'Organiser les temps morts pour apaiser les tensions et réorganiser', duree: '1h' },
    { sequence: 'Responsabilité et Leadership', seanceNumber: 10, objectif: 'Rechercher l’excellence au service d’un jeu fluide et respectueux', duree: '1h' },
    { sequence: 'Responsabilité et Leadership', seanceNumber: 11, objectif: 'Finalisation de la préparation pour le tournoi dans un esprit festif', duree: '1h' },
    { sequence: 'Evaluation sommative', seanceNumber: 12, objectif: 'Bilan final : Leadership, Efficience stratégique et Engagement citoyen', duree: '1h' },
  ]
};
